name: KiwisMusicPlayer
authors:
  - KiwiLetsPlay
website: kiwiletsplay.de
description: Play your favorite music easily via the GUI, use the Minecraft internal music or use the texture pack to add your own music
main: de.Kiwi.MusicPlayer.Main.main
version: 1.0
api-version: 1.17
default-permission: kiwi.Muisc.Use
commands:
  music:
    permission-message: You Dont hav the permissions To Play Music
    description: Open The GUI